# CMake generated Testfile for 
# Source directory: C:/Users/krzyc/.codex/worktrees/54f1/water-gateway/tests/host
# Build directory: C:/Users/krzyc/.codex/worktrees/54f1/water-gateway/tests/host/build-codex
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_config_validation "C:/Users/krzyc/.codex/worktrees/54f1/water-gateway/tests/host/build-codex/test_config_validation.exe")
set_tests_properties(test_config_validation PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/krzyc/.codex/worktrees/54f1/water-gateway/tests/host/CMakeLists.txt;74;add_test;C:/Users/krzyc/.codex/worktrees/54f1/water-gateway/tests/host/CMakeLists.txt;78;add_host_test;C:/Users/krzyc/.codex/worktrees/54f1/water-gateway/tests/host/CMakeLists.txt;0;")
add_test(test_config_migration "C:/Users/krzyc/.codex/worktrees/54f1/water-gateway/tests/host/build-codex/test_config_migration.exe")
set_tests_properties(test_config_migration PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/krzyc/.codex/worktrees/54f1/water-gateway/tests/host/CMakeLists.txt;74;add_test;C:/Users/krzyc/.codex/worktrees/54f1/water-gateway/tests/host/CMakeLists.txt;84;add_host_test;C:/Users/krzyc/.codex/worktrees/54f1/water-gateway/tests/host/CMakeLists.txt;0;")
add_test(test_config_store_status "C:/Users/krzyc/.codex/worktrees/54f1/water-gateway/tests/host/build-codex/test_config_store_status.exe")
set_tests_properties(test_config_store_status PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/krzyc/.codex/worktrees/54f1/water-gateway/tests/host/CMakeLists.txt;74;add_test;C:/Users/krzyc/.codex/worktrees/54f1/water-gateway/tests/host/CMakeLists.txt;90;add_host_test;C:/Users/krzyc/.codex/worktrees/54f1/water-gateway/tests/host/CMakeLists.txt;0;")
add_test(test_dedup "C:/Users/krzyc/.codex/worktrees/54f1/water-gateway/tests/host/build-codex/test_dedup.exe")
set_tests_properties(test_dedup PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/krzyc/.codex/worktrees/54f1/water-gateway/tests/host/CMakeLists.txt;74;add_test;C:/Users/krzyc/.codex/worktrees/54f1/water-gateway/tests/host/CMakeLists.txt;99;add_host_test;C:/Users/krzyc/.codex/worktrees/54f1/water-gateway/tests/host/CMakeLists.txt;0;")
add_test(test_mqtt_payloads "C:/Users/krzyc/.codex/worktrees/54f1/water-gateway/tests/host/build-codex/test_mqtt_payloads.exe")
set_tests_properties(test_mqtt_payloads PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/krzyc/.codex/worktrees/54f1/water-gateway/tests/host/CMakeLists.txt;74;add_test;C:/Users/krzyc/.codex/worktrees/54f1/water-gateway/tests/host/CMakeLists.txt;105;add_host_test;C:/Users/krzyc/.codex/worktrees/54f1/water-gateway/tests/host/CMakeLists.txt;0;")
add_test(test_auth_helpers "C:/Users/krzyc/.codex/worktrees/54f1/water-gateway/tests/host/build-codex/test_auth_helpers.exe")
set_tests_properties(test_auth_helpers PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/krzyc/.codex/worktrees/54f1/water-gateway/tests/host/CMakeLists.txt;74;add_test;C:/Users/krzyc/.codex/worktrees/54f1/water-gateway/tests/host/CMakeLists.txt;113;add_host_test;C:/Users/krzyc/.codex/worktrees/54f1/water-gateway/tests/host/CMakeLists.txt;0;")
add_test(test_auth_login_policy "C:/Users/krzyc/.codex/worktrees/54f1/water-gateway/tests/host/build-codex/test_auth_login_policy.exe")
set_tests_properties(test_auth_login_policy PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/krzyc/.codex/worktrees/54f1/water-gateway/tests/host/CMakeLists.txt;74;add_test;C:/Users/krzyc/.codex/worktrees/54f1/water-gateway/tests/host/CMakeLists.txt;123;add_host_test;C:/Users/krzyc/.codex/worktrees/54f1/water-gateway/tests/host/CMakeLists.txt;0;")
add_test(test_health_logic "C:/Users/krzyc/.codex/worktrees/54f1/water-gateway/tests/host/build-codex/test_health_logic.exe")
set_tests_properties(test_health_logic PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/krzyc/.codex/worktrees/54f1/water-gateway/tests/host/CMakeLists.txt;74;add_test;C:/Users/krzyc/.codex/worktrees/54f1/water-gateway/tests/host/CMakeLists.txt;133;add_host_test;C:/Users/krzyc/.codex/worktrees/54f1/water-gateway/tests/host/CMakeLists.txt;0;")
add_test(test_wmbus_pipeline "C:/Users/krzyc/.codex/worktrees/54f1/water-gateway/tests/host/build-codex/test_wmbus_pipeline.exe")
set_tests_properties(test_wmbus_pipeline PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/krzyc/.codex/worktrees/54f1/water-gateway/tests/host/CMakeLists.txt;74;add_test;C:/Users/krzyc/.codex/worktrees/54f1/water-gateway/tests/host/CMakeLists.txt;139;add_host_test;C:/Users/krzyc/.codex/worktrees/54f1/water-gateway/tests/host/CMakeLists.txt;0;")
add_test(test_meter_registry "C:/Users/krzyc/.codex/worktrees/54f1/water-gateway/tests/host/build-codex/test_meter_registry.exe")
set_tests_properties(test_meter_registry PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/krzyc/.codex/worktrees/54f1/water-gateway/tests/host/CMakeLists.txt;74;add_test;C:/Users/krzyc/.codex/worktrees/54f1/water-gateway/tests/host/CMakeLists.txt;145;add_host_test;C:/Users/krzyc/.codex/worktrees/54f1/water-gateway/tests/host/CMakeLists.txt;0;")
add_test(test_ota_manager "C:/Users/krzyc/.codex/worktrees/54f1/water-gateway/tests/host/build-codex/test_ota_manager.exe")
set_tests_properties(test_ota_manager PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/krzyc/.codex/worktrees/54f1/water-gateway/tests/host/CMakeLists.txt;74;add_test;C:/Users/krzyc/.codex/worktrees/54f1/water-gateway/tests/host/CMakeLists.txt;153;add_host_test;C:/Users/krzyc/.codex/worktrees/54f1/water-gateway/tests/host/CMakeLists.txt;0;")
add_test(test_metrics_service "C:/Users/krzyc/.codex/worktrees/54f1/water-gateway/tests/host/build-codex/test_metrics_service.exe")
set_tests_properties(test_metrics_service PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/krzyc/.codex/worktrees/54f1/water-gateway/tests/host/CMakeLists.txt;74;add_test;C:/Users/krzyc/.codex/worktrees/54f1/water-gateway/tests/host/CMakeLists.txt;160;add_host_test;C:/Users/krzyc/.codex/worktrees/54f1/water-gateway/tests/host/CMakeLists.txt;0;")
add_test(test_radio_state_machine "C:/Users/krzyc/.codex/worktrees/54f1/water-gateway/tests/host/build-codex/test_radio_state_machine.exe")
set_tests_properties(test_radio_state_machine PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/krzyc/.codex/worktrees/54f1/water-gateway/tests/host/CMakeLists.txt;74;add_test;C:/Users/krzyc/.codex/worktrees/54f1/water-gateway/tests/host/CMakeLists.txt;166;add_host_test;C:/Users/krzyc/.codex/worktrees/54f1/water-gateway/tests/host/CMakeLists.txt;0;")
